# Generated by Django 3.1.1 on 2020-09-30 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=60, verbose_name='Nome do Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('pictureProduct', models.ImageField(default='default/default1.png', upload_to='products/', verbose_name='Imagem')),
                ('description', models.TextField(max_length=120, verbose_name='Descrição')),
                ('date', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
